export const majors = [
    "Accounting",
    "Aerospace Engineering",
    "African American Studies",
    "Agriculture",
    "Anthropology",
    "Applied Mathematics",
    "Architecture",
    "Art History",
    "Astrophysics",
    "Biochemistry",
    "Bioengineering",
    "Biology",
    "Biomedical Engineering",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Classics",
    "Communications",
    "Computer Engineering",
    "Computer Science",
    "Creative Writing",
    "Criminal Justice",
    "Data Science",
    "Dentistry (Pre-Dental)",
    "Design",
    "Economics",
    "Education",
    "Electrical Engineering",
    "English Literature",
    "Environmental Science",
    "Film Studies",
    "Finance",
    "Fine Arts",
    "Gender Studies",
    "Geography",
    "Geology",
    "Graphic Design",
    "Health Sciences",
    "History",
    "Hospitality Management",
    "Human Resources",
    "Industrial Engineering",
    "Information Technology",
    "International Relations",
    "Journalism",
    "Kinesiology",
    "Law (Pre-Law)",
    "Linguistics",
    "Management",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Medicine (Pre-Med)",
    "Music",
    "Neuroscience",
    "Nursing",
    "Nutrition",
    "Philosophy",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Health",
    "Public Policy",
    "Religious Studies",
    "Robotics",
    "Sociology",
    "Software Engineering",
    "Statistics",
    "Studio Art",
    "Supply Chain Management",
    "Theater",
    "Undecided",
    "Urban Planning",
    "Veterinary Science",
    "Zoology"
];
