export const MAJORS = [
    'Accounting',
    'Aerospace Engineering',
    'African American Studies',
    'Agriculture',
    'Anthropology',
    'Applied Mathematics',
    'Architecture',
    'Art History',
    'Asian Studies',
    'Astronomy',
    'Biochemistry',
    'Bioengineering',
    'Biology',
    'Biomedical Engineering',
    'Biotechnology',
    'Business Administration',
    'Business Analytics',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Classics',
    'Cognitive Science',
    'Communications',
    'Computer Engineering',
    'Computer Science',
    'Criminal Justice',
    'Cybersecurity',
    'Data Science',
    'Dentistry (Pre-Dental)',
    'Design',
    'Drama / Theater Arts',
    'Economics',
    'Education',
    'Electrical Engineering',
    'English Literature',
    'Environmental Engineering',
    'Environmental Science',
    'Environmental Studies',
    'Ethics, Politics, and Economics',
    'Film Studies',
    'Finance',
    'Forensic Science',
    'French',
    'Gender Studies',
    'Genetics',
    'Geography',
    'Geology',
    'German',
    'Global / International Studies',
    'Graphic Design',
    'Health Science',
    'History',
    'Industrial Engineering',
    'Information Systems',
    'Information Technology',
    'International Business',
    'International Relations',
    'Journalism',
    'Kinesiology',
    'Law (Pre-Law)',
    'Linguistics',
    'Management',
    'Marine Biology',
    'Marketing',
    'Materials Science',
    'Mathematics',
    'Mechanical Engineering',
    'Media Studies',
    'Medicine (Pre-Med)',
    'Microbiology',
    'Music',
    'Music Performance',
    'Neuroscience',
    'Nuclear Engineering',
    'Nursing',
    'Nutrition',
    'Oceanography',
    'Operations Research',
    'Pharmacy (Pre-Pharm)',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Public Health',
    'Public Policy',
    'Religious Studies',
    'Robotics',
    'Social Work',
    'Sociology',
    'Software Engineering',
    'Spanish',
    'Sports Management',
    'Statistics',
    'Studio Art',
    'Supply Chain Management',
    'Sustainability',
    'Theater',
    'Theology',
    'Urban Planning',
    'Veterinary Science (Pre-Vet)',
    'Visual Arts',
    'Women\'s Studies',
    'Zoology'
];
