// src/lib/config/schools.ts
export type SchoolDecision = 'admit' | 'deny';

export interface SchoolConfig {
	slug: string;
	schoolName: string;
	logoPrimary: string;
	logoSecondary: string;
	primaryColor: string;
	admissionsId: string;
	financialAidId: string;
	bannerText: string;
	noticeText: string;
	statusLastPosted: string;
	statusLinkLabel: string;
	decision: SchoolDecision;
	footerDomain: string;
	difficulty: number; // 1-10 scale
	baseRate: number; // Decimal (e.g. 0.04)
}

export const schoolConfigs: Record<string, SchoolConfig> = {
	harvard: {
		slug: 'harvard',
		schoolName: 'Harvard College',
		logoPrimary: 'Harvard',
		logoSecondary: 'COLLEGE ADMISSIONS',
		primaryColor: '#A51C30',
		admissionsId: 'H-2026-072951',
		financialAidId: 'FA-H-567890',
		bannerText: 'Thank you for applying to Harvard College.',
		noticeText:
			'Admission decisions for Regular Decision candidates will be available Sunday, March 29 at 7:00 p.m. Eastern Time.',
		statusLastPosted: 'March 15, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'deny',
		footerDomain: 'harvard.edu',
		difficulty: 10,
		baseRate: 0.034
	},
	stanford: {
		slug: 'stanford',
		schoolName: 'Stanford University',
		logoPrimary: 'Stanford',
		logoSecondary: 'UNDERGRADUATE ADMISSION',
		primaryColor: '#8C1515',
		admissionsId: 'S-2026-068417',
		financialAidId: 'FA-S-123456',
		bannerText: 'Thank you for submitting your application to Stanford University.',
		noticeText:
			'Admission decisions for first-year applicants will be available Friday, March 27 at 4:00 p.m. Pacific Time.',
		statusLastPosted: 'March 14, 2026',
		statusLinkLabel: 'View Admission Decision >>',
		decision: 'deny',
		footerDomain: 'stanford.edu',
		difficulty: 10,
		baseRate: 0.037
	},
	mit: {
		slug: 'mit',
		schoolName: 'Massachusetts Institute of Technology',
		logoPrimary: 'MIT',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#A31F34',
		admissionsId: 'MIT-2026-041286',
		financialAidId: 'FA-MIT-246810',
		bannerText: 'Thank you for applying to the Massachusetts Institute of Technology.',
		noticeText:
			'MIT Admissions decisions will be posted in your MyMIT account on Pi Day at 6:28 p.m. ET.',
		statusLastPosted: 'March 14, 2026',
		statusLinkLabel: 'View Your Decision >>',
		decision: 'deny',
		footerDomain: 'mit.edu',
		difficulty: 10,
		baseRate: 0.04
	},
	princeton: {
		slug: 'princeton',
		schoolName: 'Princeton University',
		logoPrimary: 'Princeton',
		logoSecondary: 'UNIVERSITY ADMISSION',
		primaryColor: '#FF8F00',
		admissionsId: 'P-2026-183627',
		financialAidId: 'FA-P-987654',
		bannerText: 'Thank you for applying to Princeton University.',
		noticeText:
			'Regular Decision results for first-year applicants will be available in the applicant portal on March 28 at 7:00 p.m. ET.',
		statusLastPosted: 'March 12, 2026',
		statusLinkLabel: 'View Simulated Status Update >>',
		decision: 'deny',
		footerDomain: 'princeton.edu',
		difficulty: 9.8,
		baseRate: 0.045
	},
	yale: {
		slug: 'yale',
		schoolName: 'Yale College',
		logoPrimary: 'Yale',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#00356B',
		admissionsId: 'Y-2026-281706',
		financialAidId: 'FA-Y-556677',
		bannerText: 'Thank you for completing your application to Yale College.',
		noticeText:
			'Your Yale admissions decision is now available in your Yale Admissions Status Portal.',
		statusLastPosted: 'March 15, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'admit',
		footerDomain: 'yale.edu',
		difficulty: 9.8,
		baseRate: 0.046
	},
	columbia: {
		slug: 'columbia',
		schoolName: 'Columbia University',
		logoPrimary: 'Columbia',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#003D6B',
		admissionsId: 'CU-2026-463215',
		financialAidId: 'FA-CU-001122',
		bannerText: 'Thank you for applying to Columbia University in the City of New York.',
		noticeText:
			'Admission decisions are now available in your applicant status page. Please log in to view your simulated decision.',
		statusLastPosted: 'March 13, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'columbia.edu',
		difficulty: 9.7,
		baseRate: 0.039
	},
	uchicago: {
		slug: 'uchicago',
		schoolName: 'The University of Chicago',
		logoPrimary: 'UChicago',
		logoSecondary: 'COLLEGE ADMISSIONS',
		primaryColor: '#800000',
		admissionsId: 'UC-2026-248061',
		financialAidId: 'FA-UC-246802',
		bannerText: 'Thank you for applying to the College at the University of Chicago.',
		noticeText:
			'A decision has been posted to your UChicago Account. For security reasons, decisions are not released by email or telephone.',
		statusLastPosted: 'March 16, 2026',
		statusLinkLabel: 'View Your UChicago Decision >>',
		decision: 'admit',
		footerDomain: 'uchicago.edu',
		difficulty: 9.6,
		baseRate: 0.05
	},
	upenn: {
		slug: 'upenn',
		schoolName: 'University of Pennsylvania',
		logoPrimary: 'Penn',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#011F5B',
		admissionsId: 'PENN-2026-624981',
		financialAidId: 'FA-PENN-112244',
		bannerText: 'Thank you for applying to the University of Pennsylvania.',
		noticeText:
			'Your admissions decision is now available in your Penn Applicant Portal. Please log in using your existing credentials.',
		statusLastPosted: 'March 13, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'deny',
		footerDomain: 'upenn.edu',
		difficulty: 9.5,
		baseRate: 0.058
	},
	caltech: {
		slug: 'caltech',
		schoolName: 'California Institute of Technology',
		logoPrimary: 'Caltech',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#FF6C0C',
		admissionsId: 'CIT-2026-390274',
		financialAidId: 'FA-CIT-333777',
		bannerText: 'Thank you for applying to the California Institute of Technology.',
		noticeText:
			'Caltech admissions decisions for first-year applicants are now available via the Beaver Breakroom portal.',
		statusLastPosted: 'March 14, 2026',
		statusLinkLabel: 'View Caltech Decision >>',
		decision: 'deny',
		footerDomain: 'caltech.edu',
		difficulty: 10,
		baseRate: 0.03
	},
	duke: {
		slug: 'duke',
		schoolName: 'Duke University',
		logoPrimary: 'Duke',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#00539B',
		admissionsId: 'DUKE-2026-570913',
		financialAidId: 'FA-DUKE-987654',
		bannerText: 'Thank you for submitting your application to Duke University!',
		noticeText:
			'Admission decisions for Regular Decision (and deferred Early Decision) candidates will be available Thursday, March 26 at 7 p.m. Eastern Time.',
		statusLastPosted: 'December 12, 2019',
		statusLinkLabel: 'View Simulated Status Update >>',
		decision: 'admit',
		footerDomain: 'duke.edu',
		difficulty: 9.4,
		baseRate: 0.06
	},
	jhu: {
		slug: 'jhu',
		schoolName: 'Johns Hopkins University',
		logoPrimary: 'Johns Hopkins',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#002D72',
		admissionsId: 'JHU-2026-386250',
		financialAidId: 'FA-JHU-889900',
		bannerText: 'Thank you for applying to Johns Hopkins University.',
		noticeText: 'Admission decisions are now available in your Johns Hopkins applicant portal.',
		statusLastPosted: 'March 15, 2026',
		statusLinkLabel: 'View Admissions Decision >>',
		decision: 'admit',
		footerDomain: 'jhu.edu',
		difficulty: 9.3,
		baseRate: 0.065
	},
	northwestern: {
		slug: 'northwestern',
		schoolName: 'Northwestern University',
		logoPrimary: 'Northwestern',
		logoSecondary: 'UNDERGRADUATE ADMISSION',
		primaryColor: '#4E2A84',
		admissionsId: 'NU-2026-214539',
		financialAidId: 'FA-NU-334455',
		bannerText: 'Thank you for applying to Northwestern University.',
		noticeText: 'Your Northwestern admissions decision is now available in your applicant portal.',
		statusLastPosted: 'March 17, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'admit',
		footerDomain: 'northwestern.edu',
		difficulty: 9.2,
		baseRate: 0.07
	},
	dartmouth: {
		slug: 'dartmouth',
		schoolName: 'Dartmouth College',
		logoPrimary: 'Dartmouth',
		logoSecondary: 'OFFICE OF ADMISSIONS',
		primaryColor: '#00693E',
		admissionsId: 'DC-2026-175384',
		financialAidId: 'FA-DC-880044',
		bannerText: 'Thank you for applying to Dartmouth College.',
		noticeText:
			'A decision has been posted to your Dartmouth applicant portal. Please log in to view it.',
		statusLastPosted: 'March 16, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'dartmouth.edu',
		difficulty: 9.3,
		baseRate: 0.062
	},
	brown: {
		slug: 'brown',
		schoolName: 'Brown University',
		logoPrimary: 'Brown',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#4E3629',
		admissionsId: 'BR-2026-356208',
		financialAidId: 'FA-BR-303030',
		bannerText: 'Thank you for applying to Brown University.',
		noticeText:
			'Your Brown decision is now available via your Brown Applicant Portal. Please sign in to view your admission decision.',
		statusLastPosted: 'March 15, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'deny',
		footerDomain: 'brown.edu',
		difficulty: 9.5,
		baseRate: 0.051
	},
	vanderbilt: {
		slug: 'vanderbilt',
		schoolName: 'Vanderbilt University',
		logoPrimary: 'Vanderbilt',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#B89D4F',
		admissionsId: 'VU-2026-481672',
		financialAidId: 'FA-VU-252525',
		bannerText: 'Thank you for applying to Vanderbilt University.',
		noticeText: 'Your Vanderbilt admissions decision is now available via your MyAppVU portal.',
		statusLastPosted: 'March 17, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'vanderbilt.edu',
		difficulty: 9.1,
		baseRate: 0.07
	},
	rice: {
		slug: 'rice',
		schoolName: 'Rice University',
		logoPrimary: 'Rice',
		logoSecondary: 'OFFICE OF ADMISSION',
		primaryColor: '#00205B',
		admissionsId: 'RU-2026-739105',
		financialAidId: 'FA-RU-161616',
		bannerText: 'Thank you for applying to Rice University.',
		noticeText: 'Rice admission decisions are available in your Rice Admission Student Portal.',
		statusLastPosted: 'March 16, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'admit',
		footerDomain: 'rice.edu',
		difficulty: 9.0,
		baseRate: 0.075
	},
	wustl: {
		slug: 'wustl',
		schoolName: 'Washington University in St. Louis',
		logoPrimary: 'WashU',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#295F2D',
		admissionsId: 'WU-2026-260483',
		financialAidId: 'FA-WU-191919',
		bannerText: 'Thank you for applying to Washington University in St. Louis.',
		noticeText:
			'A status update has been posted to your WashU Pathway portal. Please log in to view your simulated decision.',
		statusLastPosted: 'March 18, 2026',
		statusLinkLabel: 'View Simulated Status Update >>',
		decision: 'admit',
		footerDomain: 'wustl.edu',
		difficulty: 8.8,
		baseRate: 0.11
	},
	cornell: {
		slug: 'cornell',
		schoolName: 'Cornell University',
		logoPrimary: 'Cornell',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#B31B1B',
		admissionsId: 'CU-2026-594317',
		financialAidId: 'FA-CU-272727',
		bannerText: 'Thank you for applying to Cornell University.',
		noticeText: 'Your admission decision is now available in your Cornell application status page.',
		statusLastPosted: 'March 15, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'deny',
		footerDomain: 'cornell.edu',
		difficulty: 9.0,
		baseRate: 0.079
	},
	ucla: {
		slug: 'ucla',
		schoolName: 'University of California, Los Angeles',
		logoPrimary: 'UCLA',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#2774AE',
		admissionsId: 'UCLA-2026-407251',
		financialAidId: 'FA-UCLA-282828',
		bannerText: 'Thank you for applying to the University of California, Los Angeles.',
		noticeText: 'Your UCLA admission decision has been posted to the UCLA Applicant Portal.',
		statusLastPosted: 'March 20, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'ucla.edu',
		difficulty: 8.5,
		baseRate: 0.09
	},
	ucberkeley: {
		slug: 'ucberkeley',
		schoolName: 'University of California, Berkeley',
		logoPrimary: 'Berkeley',
		logoSecondary: 'OFFICE OF UNDERGRADUATE ADMISSIONS',
		primaryColor: '#003262',
		admissionsId: 'UCB-2026-618490',
		financialAidId: 'FA-UCB-292929',
		bannerText: 'Thank you for applying to the University of California, Berkeley.',
		noticeText: 'Your UC Berkeley admission decision is now available in the MAP@Berkeley portal.',
		statusLastPosted: 'March 20, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'admit',
		footerDomain: 'berkeley.edu',
		difficulty: 8.7,
		baseRate: 0.11
	},
	wwu: {
		slug: 'wwu',
		schoolName: 'Western Washington University',
		logoPrimary: 'Western',
		logoSecondary: 'ADMISSIONS',
		primaryColor: '#003F87',
		admissionsId: 'WWU-2026-159340',
		financialAidId: 'FA-WWU-445566',
		bannerText: 'Thank you for applying to Western Washington University.',
		noticeText: 'Your admission decision is now available in your portal.',
		statusLastPosted: 'March 15, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'wwu.edu',
		difficulty: 4.0,
		baseRate: 0.85
	},
	georgiatech: {
		slug: 'georgiatech',
		schoolName: 'Georgia Institute of Technology',
		logoPrimary: 'Georgia Tech',
		logoSecondary: 'UNDERGRADUATE ADMISSION',
		primaryColor: '#003057',
		admissionsId: 'GT-2026-371852',
		financialAidId: 'FA-GT-102030',
		bannerText: 'Thank you for applying to the Georgia Institute of Technology.',
		noticeText:
			'A decision has been posted to your Georgia Tech application status page. Please log in to view your simulated decision.',
		statusLastPosted: 'March 8, 2026',
		statusLinkLabel: 'View Simulated Status Update >>',
		decision: 'deny',
		footerDomain: 'gatech.edu',
		difficulty: 8.5,
		baseRate: 0.16
	},
	nyu: {
		slug: 'nyu',
		schoolName: 'New York University',
		logoPrimary: 'NYU',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#57068C',
		admissionsId: 'NYU-2026-482964',
		financialAidId: 'FA-NYU-203040',
		bannerText: 'Thank you for applying to New York University.',
		noticeText:
			'Your NYU admission decision is now available. Please log in to your NYU Albert applicant portal to view it.',
		statusLastPosted: 'March 26, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'nyu.edu',
		difficulty: 8.5,
		baseRate: 0.12
	},
	usc: {
		slug: 'usc',
		schoolName: 'University of Southern California',
		logoPrimary: 'USC',
		logoSecondary: 'UNDERGRADUATE ADMISSION',
		primaryColor: '#990000',
		admissionsId: 'USC-2026-519273',
		financialAidId: 'FA-USC-304050',
		bannerText: 'Thank you for applying to the University of Southern California.',
		noticeText:
			'Your USC admission decision is now available in your USC Applicant Portal. Fight On!',
		statusLastPosted: 'March 27, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'usc.edu',
		difficulty: 8.6,
		baseRate: 0.1
	},
	georgetown: {
		slug: 'georgetown',
		schoolName: 'Georgetown University',
		logoPrimary: 'Georgetown',
		logoSecondary: 'OFFICE OF UNDERGRADUATE ADMISSIONS',
		primaryColor: '#041E42',
		admissionsId: 'GU-2026-630184',
		financialAidId: 'FA-GU-405060',
		bannerText: 'Thank you for applying to Georgetown University.',
		noticeText:
			'Your admission decision is now available on your Georgetown Application Status page.',
		statusLastPosted: 'March 20, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'admit',
		footerDomain: 'georgetown.edu',
		difficulty: 8.8,
		baseRate: 0.12
	},
	notredame: {
		slug: 'notredame',
		schoolName: 'University of Notre Dame',
		logoPrimary: 'Notre Dame',
		logoSecondary: 'UNDERGRADUATE ADMISSIONS',
		primaryColor: '#0C2340',
		admissionsId: 'ND-2026-741295',
		financialAidId: 'FA-ND-506070',
		bannerText: 'Thank you for applying to the University of Notre Dame.',
		noticeText:
			'A decision has been posted to your Notre Dame applicant status portal. Please log in to view it.',
		statusLastPosted: 'March 25, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'nd.edu',
		difficulty: 8.6,
		baseRate: 0.12
	},
	emory: {
		slug: 'emory',
		schoolName: 'Emory University',
		logoPrimary: 'Emory',
		logoSecondary: 'OFFICE OF ADMISSION',
		primaryColor: '#012169',
		admissionsId: 'EU-2026-852306',
		financialAidId: 'FA-EU-607080',
		bannerText: 'Thank you for applying to Emory University.',
		noticeText:
			'Your Emory admission decision is now available in your applicant portal. Please log in to view it.',
		statusLastPosted: 'March 25, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'emory.edu',
		difficulty: 8.4,
		baseRate: 0.13
	},
	uva: {
		slug: 'uva',
		schoolName: 'University of Virginia',
		logoPrimary: 'UVA',
		logoSecondary: 'OFFICE OF ADMISSION',
		primaryColor: '#232D4B',
		admissionsId: 'UVA-2026-963417',
		financialAidId: 'FA-UVA-708090',
		bannerText: 'Thank you for applying to the University of Virginia.',
		noticeText:
			'Your admission decision is now available in your MyUVA applicant portal. Please log in to view it.',
		statusLastPosted: 'March 21, 2026',
		statusLinkLabel: 'View Status >>',
		decision: 'admit',
		footerDomain: 'virginia.edu',
		difficulty: 8.0,
		baseRate: 0.17
	},
	cmu: {
		slug: 'cmu',
		schoolName: 'Carnegie Mellon University',
		logoPrimary: 'Carnegie Mellon',
		logoSecondary: 'OFFICE OF ADMISSION',
		primaryColor: '#C41230',
		admissionsId: 'CMU-2026-174528',
		financialAidId: 'FA-CMU-809000',
		bannerText: 'Thank you for applying to Carnegie Mellon University.',
		noticeText:
			'Your admission decision is now available. Please log in to your CMU applicant portal to view it.',
		statusLastPosted: 'March 15, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'cmu.edu',
		difficulty: 8.9,
		baseRate: 0.11
	},
	umich: {
		slug: 'umich',
		schoolName: 'University of Michigan',
		logoPrimary: 'Michigan',
		logoSecondary: 'OFFICE OF UNDERGRADUATE ADMISSIONS',
		primaryColor: '#00274C',
		admissionsId: 'UM-2026-285639',
		financialAidId: 'FA-UM-900010',
		bannerText: 'Thank you for applying to the University of Michigan.',
		noticeText:
			'Your admission decision is now available in your U-M applicant portal. Please log in to view it.',
		statusLastPosted: 'March 28, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'umich.edu',
		difficulty: 8.0,
		baseRate: 0.18
	},
	unc: {
		slug: 'unc',
		schoolName: 'University of North Carolina at Chapel Hill',
		logoPrimary: 'UNC',
		logoSecondary: 'OFFICE OF UNDERGRADUATE ADMISSIONS',
		primaryColor: '#4B9CD3',
		admissionsId: 'UNC-2026-396740',
		financialAidId: 'FA-UNC-100020',
		bannerText: 'Thank you for applying to the University of North Carolina at Chapel Hill.',
		noticeText:
			'A decision has been posted to your UNC applicant portal. Please log in to view your simulated decision.',
		statusLastPosted: 'March 20, 2026',
		statusLinkLabel: 'View Simulated Status Update >>',
		decision: 'deny',
		footerDomain: 'unc.edu',
		difficulty: 7.8,
		baseRate: 0.19
	},
	ucsd: {
		slug: 'ucsd',
		schoolName: 'University of California, San Diego',
		logoPrimary: 'UC San Diego',
		logoSecondary: 'OFFICE OF ADMISSIONS',
		primaryColor: '#182B49',
		admissionsId: 'UCSD-2026-407851',
		financialAidId: 'FA-UCSD-200030',
		bannerText: 'Thank you for applying to the University of California, San Diego.',
		noticeText:
			'Your UC San Diego admission decision is now available in your applicant portal.',
		statusLastPosted: 'March 20, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'ucsd.edu',
		difficulty: 7.5,
		baseRate: 0.24
	},
	uci: {
		slug: 'uci',
		schoolName: 'University of California, Irvine',
		logoPrimary: 'UC Irvine',
		logoSecondary: 'OFFICE OF ADMISSIONS',
		primaryColor: '#0064A4',
		admissionsId: 'UCI-2026-518962',
		financialAidId: 'FA-UCI-300040',
		bannerText: 'Thank you for applying to the University of California, Irvine.',
		noticeText:
			'Your UC Irvine admission decision is now available in your applicant portal.',
		statusLastPosted: 'March 20, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'uci.edu',
		difficulty: 7.3,
		baseRate: 0.21
	},
	ucdavis: {
		slug: 'ucdavis',
		schoolName: 'University of California, Davis',
		logoPrimary: 'UC Davis',
		logoSecondary: 'OFFICE OF ADMISSIONS',
		primaryColor: '#022851',
		admissionsId: 'UCD-2026-629073',
		financialAidId: 'FA-UCD-400050',
		bannerText: 'Thank you for applying to the University of California, Davis.',
		noticeText:
			'Your UC Davis admission decision is now available in your applicant portal.',
		statusLastPosted: 'March 20, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'ucdavis.edu',
		difficulty: 6.5,
		baseRate: 0.37
	},
	wakeforest: {
		slug: 'wakeforest',
		schoolName: 'Wake Forest University',
		logoPrimary: 'Wake Forest',
		logoSecondary: 'OFFICE OF ADMISSIONS',
		primaryColor: '#9E7E38',
		admissionsId: 'WFU-2026-730184',
		financialAidId: 'FA-WFU-101020',
		bannerText: 'Thank you for applying to Wake Forest University.',
		noticeText:
			'Your admission decision is now available in your Wake Forest applicant status portal.',
		statusLastPosted: 'March 24, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'wfu.edu',
		difficulty: 7.5,
		baseRate: 0.21
	},
	uf: {
		slug: 'uf',
		schoolName: 'University of Florida',
		logoPrimary: 'Florida',
		logoSecondary: 'OFFICE OF ADMISSIONS',
		primaryColor: '#0021A5',
		admissionsId: 'UF-2026-841295',
		financialAidId: 'FA-UF-500060',
		bannerText: 'Thank you for applying to the University of Florida.',
		noticeText:
			'Your admission decision is now available in your University of Florida applicant portal.',
		statusLastPosted: 'February 27, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'ufl.edu',
		difficulty: 7.0,
		baseRate: 0.23
	},
	wisconsin: {
		slug: 'wisconsin',
		schoolName: 'University of Wisconsin-Madison',
		logoPrimary: 'Wisconsin',
		logoSecondary: 'OFFICE OF ADMISSIONS AND RECRUITMENT',
		primaryColor: '#C5050C',
		admissionsId: 'UW-2026-163417',
		financialAidId: 'FA-UW-700080',
		bannerText: 'Thank you for applying to the University of Wisconsin-Madison.',
		noticeText:
			'Your admission decision is now available in your MyUW applicant portal.',
		statusLastPosted: 'March 15, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'wisc.edu',
		difficulty: 6.0,
		baseRate: 0.45
	},
	purdue: {
		slug: 'purdue',
		schoolName: 'Purdue University',
		logoPrimary: 'Purdue',
		logoSecondary: 'OFFICE OF ADMISSIONS',
		primaryColor: '#000000',
		admissionsId: 'PU-2026-274528',
		financialAidId: 'FA-PU-800090',
		bannerText: 'Thank you for applying to Purdue University.',
		noticeText:
			'Your admission decision is now available in your Purdue applicant portal.',
		statusLastPosted: 'March 10, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'purdue.edu',
		difficulty: 5.8,
		baseRate: 0.5
	},
	osu: {
		slug: 'osu',
		schoolName: 'The Ohio State University',
		logoPrimary: 'Ohio State',
		logoSecondary: 'OFFICE OF UNDERGRADUATE ADMISSIONS',
		primaryColor: '#BB0000',
		admissionsId: 'OSU-2026-385639',
		financialAidId: 'FA-OSU-900000',
		bannerText: 'Thank you for applying to The Ohio State University.',
		noticeText:
			'Your admission decision is now available in your Ohio State applicant portal.',
		statusLastPosted: 'March 12, 2026',
		statusLinkLabel: 'View Simulated Decision >>',
		decision: 'admit',
		footerDomain: 'osu.edu',
		difficulty: 5.5,
		baseRate: 0.53
	}
};
